# Generated by Django 2.2 on 2019-04-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='manufacture/%Y/%m/%d/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('currency', models.CharField(max_length=16)),
                ('guarantee', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('in_case', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='equipment/%Y/%m/%d/')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Manufacturer')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.SubGroup')),
                ('type_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Type')),
            ],
        ),
    ]
