# Generated by Django 2.2 on 2019-04-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='guarantee',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='in_case',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='EquipmentMarketConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=512)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Market')),
            ],
        ),
    ]
