# Generated by Django 2.2 on 2019-04-01 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='manufacture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='equipment.Manufacturer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='guarantee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
    ]
