# Generated by Django 2.2 on 2019-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20190401_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='guarantee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
